name: zyen

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 9999999999999999999999

    steps:

    - name: Download

      run: |

        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

        Invoke-WebRequest https://raw.githubusercontent.com/zzlastgame/zyenRDP/main/credentials.bat -OutFile credentials.bat

    - name: Extract

      run: Expand-Archive ngrok.zip

      

    - name: Auth

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

        

    - name: Enable TS

      run: | 

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Create Tunnel

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'

      

    - name: Login credentials info

      run: cmd /c credentials.bat

      

    - name: Done

      run: | 

        Invoke-WebRequest https://raw.githubusercontent.com/maudyewe/kuda/main/wewe.ps1 -OutFile loop.ps1

        ./loop.ps1
